### ISSUE TITLE
A bug about image saving 

### ISSUE THREAD

**Issue by ChuangbinC** [jzengust/RGBD2Normal#2]
Hi, @jzengust 
It seems have a code error in `change_channel` function in `utils.py`. The original  return result of new_norm is a `list` which cann't be saved in `misc.imsave` in python3.
```
def change_channel(outputs_norm, scale=1):
    row,col,channel=outputs_norm.shape
    nx = np.ones((row,col)) - outputs_norm[:, :, 0]
    ny = np.ones((row,col)) - outputs_norm[:, :, 1]
    nz = outputs_norm[:, :, 2]
    # original : new_norm = [nx, nz, ny]
    new_norm = np.concatenate((np.expand_dims(nx,2), np.expand_dims(nz,2), np.expand_dims(ny,2)),axis=2)
    return new_norm
```

**Comment by jzengust** [comment]
Hi @ChuangbinC 

The code is tested in python 2, but i suppose in python 3 the result from np.concatenate() should not be a list though. Could you please provide more details so that i can help you with?

Best,
Jin
